# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-13 15:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplikacja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_utworzenia', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Aplikant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('wiek', models.IntegerField(blank=True, default=0)),
                ('wyksztalcenie', models.CharField(blank=True, default='', max_length=100)),
                ('telefon', models.CharField(blank=True, default='', max_length=20)),
                ('miasto', models.CharField(blank=True, default='', max_length=100)),
                ('panstwo', models.CharField(blank=True, default='', max_length=100)),
                ('opis', models.TextField(blank=True, default='')),
                ('cv', models.FileField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplikant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_firmy', models.CharField(max_length=100)),
                ('miasto', models.CharField(max_length=100)),
                ('ulica', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firma', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branza', models.CharField(max_length=200)),
                ('lokalizacja', models.CharField(max_length=100)),
                ('wakat', models.CharField(max_length=100)),
                ('wynagrodzenie', models.FloatField(default=0)),
                ('opis', models.TextField(blank=True, max_length=1000)),
                ('data_utworzenia', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oferta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='aplikacja',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oferta_fk', to='projekt.Oferta'),
        ),
        migrations.AddField(
            model_name='aplikacja',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aplikacja',
            name='user_oferta_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_owner_fk', to=settings.AUTH_USER_MODEL),
        ),
    ]
