# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-29 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aplikacja',
            old_name='user_owner',
            new_name='user_oferta_owner',
        ),
    ]
