# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-06 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0002_auto_20180506_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraplication',
            name='pochodzenie',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='useraplication',
            name='wiek',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='useraplication',
            name='wyksztalcenie',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
