# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-22 18:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0002_remove_aplikant_pochodzenie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplikant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplikant', to=settings.AUTH_USER_MODEL),
        ),
    ]
