# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-06 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0002_auto_20180529_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='opis',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
