# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-06 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0003_auto_20180506_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraplication',
            name='wiek',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
