# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0003_auto_20180404_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplikant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('wiek', models.IntegerField()),
                ('wyksztalcenie', models.CharField(max_length=100)),
                ('pochodzenie', models.CharField(max_length=100)),
            ],
        ),
    ]
