# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-06 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0004_auto_20180506_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
